apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lomztein/fortune_cookie_fe:latest
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_DNS
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap
              key: BACKEND_DNS
        - name: BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap
              key: BACKEND_PORT
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080