apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/conf/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
      name: redis-port
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /conf
      name: config
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: redis-pvc
    - name: config
      configMap:
        name: redis-config
        items:
        - key: redis-config
          path: redis.conf