apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: lomztein/fortune_cookie_be:latest
        ports:
        - containerPort: 9000
        env:
        - name: REDIS_DNS
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: REDIS_DNS
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9000
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 5
